services:
  goapp:
    container_name: goapp
    image: goapp:1.0.1
    build:
      context: .
      dockerfile: backend/go.dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    ports:
      - 3001:3001
    depends_on:
      - db
    restart: always

  db:
    container_name: db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}